apiVersion: v1
kind: Namespace
metadata:
  name: ibm-bas
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: bas-operator-group
  namespace: ibm-bas
spec:
  targetNamespaces:
    - ibm-bas
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: behavior-analytics-services-operator-certified
  namespace: ibm-bas
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: behavior-analytics-services-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: behavior-analytics-services-operator.v1.1.0
