apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cp-data-operator
  namespace: cpd-meta-ops
spec:
  channel: v1.0
  installPlanApproval: Automatic
  name: ibm-cp-data-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-cp-data-operator.v1.0.8