apiVersion: v1
kind: Namespace
metadata:
  name: strimzi-kafka
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: strimzi-operator-group
  namespace: strimzi-kafka
spec:
  targetNamespaces:
    - strimzi-kafka
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-cluster-operator.v0.22.1
  namespace: strimzi-kafka
spec:
  channel: strimzi-0.22.x
  installPlanApproval: Automatic
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: strimzi-cluster-operator.v0.22.1
