apiVersion: v1
baseDomain: mydomain.io
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      type: Standard_D8s_v4
      osDisk:
        diskSizeGB: 512
      zones:
        - "1"
        - "2"
        - "3"
  replicas: 3
compute:
  - hyperthreading: Enabled
    name: worker
    platform:
      azure:
        type: Standard_D8s_v4
        osDisk:
          diskSizeGB: 512
        zones:
          - "1"
          - "2"
          - "3"
    replicas: 0
metadata:
  name: devcluster
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
  hostPrefix: 23
  machineNetwork:
    - cidr: 10.0.0.0/24
    - cidr: 10.0.2.0/23
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: airgap-maximo
    resourceGroupName: airgap-cluster
    virtualNetwork: airgap-vnet
    networkResourceGroupName: airgap-maximo
    controlPlaneSubnet: control
    computeSubnet: workers
    cloudName: AzurePublicCloud
    outboundType: UserDefinedRouting
    region: eastus
    publish: Internal
pullSecret: |
  insert your pull secret
sshKey: |
  insert your public key
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  insert your root CA cert
  -----END CERTIFICATE-----
imageContentSources:
  - mirrors:
      - mymirror.azurecr.io:443/ocp4/openshift48
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
      - mymirror.azurecr.io:443/ocp4/openshift48
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
