apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: $clusterName-worker-eastus$zone
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: $clusterName
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: $numReplicas
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: $clusterName
      machine.openshift.io/cluster-api-machineset: $clusterName-worker-eastus$zone
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: $clusterName
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: $clusterName-worker-eastus$zone
    spec:
      metadata: {}
      providerSpec:
        value:
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: $clusterName-rg
          publicLoadBalancer: $clusterName
          userDataSecret:
            name: worker-user-data
          vnet: $clusterName-vnet
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: "$zone"
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: $clusterName-rg
          kind: AzureMachineProviderSpec
          location: eastus
          vmSize: Standard_D8s_v3
          image:
            offer: ''
            publisher: ''
            resourceID: >-
              /resourceGroups/$clusterName-rg/providers/Microsoft.Compute/images/$clusterName
            sku: ''
            version: ''
          managedIdentity: $clusterName-identity
          subnet: $clusterName-worker-subnet
          apiVersion: azureproviderconfig.openshift.io/v1beta1