apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefiles
provisioner: kubernetes.io/azure-file
reclaimPolicy: Delete
mountOptions:
  - dir_mode=0777
  - file_mode=0777
volumeBindingMode: Immediate