apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefiles-premium
provisioner: kubernetes.io/azure-file
parameters:
  protocol: nfs
  networkEndpointType: privateEndpoint
  location: $deployRegion
  resourceGroup: $resourceGroupName
  skuName: Premium_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true