kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:controller:persistent-volume-binder
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'true'
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - persistentvolumes
  - verbs:
      - update
    apiGroups:
      - ''
    resources:
      - persistentvolumes/status
  - verbs:
      - get
      - list
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
  - verbs:
      - update
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims/status
  - verbs:
      - create
      - delete
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
  - verbs:
      - create
      - delete
      - get
      - update
    apiGroups:
      - ''
    resources:
      - endpoints
  - verbs:
      - create
      - delete
      - get
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - create
      - delete
      - get
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - watch
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - create
      - patch
      - update
    apiGroups:
      - ''
      - events.k8s.io
    resources:
      - events