apiVersion: v1
kind: Namespace
metadata:
  name: ibm-sls
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sls-operator-group
  namespace: ibm-sls
spec:
  targetNamespaces:
    - ibm-sls
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-truststore-mgr-1.x-ibm-operator-catalog-openshift-marketplace
  namespace: ibm-sls
spec:
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  name: ibm-truststore-mgr
  channel: 1.x
  startingCSV: ibm-truststore-mgr.v1.0.0
  installPlanApproval: Automatic
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-sls
  namespace: ibm-sls
spec:
  channel: 3.x
  installPlanApproval: Automatic
  name: ibm-sls
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-sls.v3.2.1
