apiVersion: config.mas.ibm.com/v1
kind: BasCfg
metadata:
  name: nonprod-bas-system
  namespace: mas-nonprod-core
spec:
  certificates:
    - alias: crt1
      crt: |
        null
  config:
    contact:
      email: DBAUMGARTEN@microsoft.com
      firstName: David
      lastName: Baumgarten
    credentials:
      secretName: nonprod-usersupplied-bas-creds-system
    url: 'https://bas-endpoint-ibm-bas.apps.$clusterName.$baseDomain'
  displayName: 'https://bas-endpoint-ibm-bas.apps.$clusterName.$baseDomain'