apiVersion: v1
kind: Namespace
metadata:
  name: mas-nonprod-core
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: mas-operator-group
  namespace: mas-nonprod-core
spec:
  targetNamespaces:
    - mas-nonprod-core
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mas.v8.6.x
  namespace: mas-nonprod-core
spec:
  channel: 8.6.x
  installPlanApproval: Automatic
  name: ibm-mas
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace