apiVersion: config.mas.ibm.com/v1
kind: SlsCfg
metadata:
  name: nonprod-sls-system
  namespace: mas-nonprod-core
spec:
  certificates:
    - alias: cert1
      crt: |
        null
    - alias: cert2
      crt: |
        null
  config:
    credentials:
      secretName: nonprod-usersupplied-sls-creds-system
    url: 'https://sls.ibm-sls.svc'
  displayName: System SLS Configuration